config/routes.rb
Rails.application.routes.draw do


  # Route to manage Attachinary
  mount Attachinary::Engine => "/attachinary"

  # Routes related to the users
  devise_for :users
  resources :users, only: [:index]

  root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  # Routes related to products
  get "products" => "products#index"
  get "products/:id" => "products#show"


  # Routes related to users management
  resources :categories

  # Routes related to the countries mangement
  resources :countries

  # Routes related to the groups mangement
  resources :groups

  # Routes related to the markets mangement
  resources :markets

  # Routes related to the nationals mangement
  resources :nationals

  # Routes related to the profils mangement
  resources :profils

  # Routes related to the post mangement
  resources :posts

  # Routes related to the regionals mangement
  resources :regionals

  # Routes related to the retailers mangement
  resources :retailers


  namespace :dynamic_select do
    get ':country_id/countries', to: 'categories#index', as: 'countries'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/national.rb
class National < ApplicationRecord
  #############################################################################
  # Data  model relationships
  #############################################################################
  
  belongs_to :retailer
  has_many :regionals

  #############################################################################
  # Controls on set data`
  #############################################################################
  
  validates :code,
            presence:true,
            uniqueness: true

  validates :label,
            presence:true,
            length: {maximum: 50}

  validates :retailer_id,
            presence:true

  #############################################################################
  # Data mangement before validation `
  #
  #############################################################################
  

  # Rq-national-003 : Before creating or updating national Info set label in the 
  # right format : not space before / first letter capitalize
  before_validation :format_label

  # Rq-national-002 : Before creating or updating national Info generate the code 
  # according the label set.
  before_validation :set_code

  
  #############################################################################
  # Scope on set data`
  #############################################################################

  # Scope on the active nationals
  scope :active, -> {
    where(:active => true)
  }

  scope :search, -> (query){
    where("code like :query or label like :query", query: "%#{query}%")
  }

  private

  def format_label
    self.label = self.label.strip.capitalize
  end 

  # Rq-national-001: Generating the central national code
  def set_code
      self.code = self.retailer.code+"-nat-"+self.label.strip.upcase[0..2]
  end
  
end

app/controllers/nationals_controller.rb
class NationalsController < ApplicationController
  before_action :find_national, only: [:show,:edit, :update, :destroy]

  # Gathering active retailers to create or update
  before_action :find_selectable_retailers, only: [:new, :edit]

  def index
    @nationals = National.all
    @nationals = @nationals.active if params[:active]
    @nationals = @nationals.search(params[:search]) if params[:search]
  end

  def show
  end

  def new
    @national = National.new
  end

  def create
    @national = National.new(national_params)
    if @national.save
      redirect_to nationals_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @national.update(national_params)
      redirect_to nationals_path
    else
      render :edit
    end
  end

  def destroy
    @national.destroy
    redirect_to nationals_path
  end


  private

  # Avoid paramters hacking
  def national_params
    params.require(:national).permit(:code,:label,:active,:description,:retailer_id)
  end

  def find_national
    @national = National.find(params[:id])
  end

  def find_selectable_retailers
  	@selectable_retailers = Retailer.all
  end 

end

app/helpers/nationals_helper.rb
module NationalsHelper
end

app/views/nationals/_national_form.html.erb
<%= simple_form_for @national do |n| %>
  <%= n.input :code, input_html: {:maxlength => 10 },:readonly => true%>
  <%= n.input :label, input_html: { maxlength: 50 } %>
  <%= n.input :active, :disabled => false%>
  <%= n.association :retailer,label:'Retailer',collection:@selectable_retailers,:readonly => false, :label_method => lambda { |retailer| "#{retailer.code} - #{retailer.label}" },include_blank: true,input_html: { id: "country-select-for-master",class: 'items-select' } %>
  <%= n.input :description, as: :text ,input_html: { maxlength: 255 } %>
  <div class="buttons-down-form">
    <%= n.button :submit, "Validate", class: "btn validate" %> 
    <button class="btn">
      <%= link_to "Back", nationals_path, class: " navbar-wagon-item navbar-wagon-link" %>
    </button>
  </div>
<% end %>

app/views/nationals/_nationals-list.html.erb
<% if @nationals.length != 0 %>
  <% @nationals.each do |national|  %>
    <div class="product">
      <div class='product-body'>
        <h3> <%= national.code %> <%= national.label %> </h3>
        <div>Active:
          <% if national.active == true%>
              <i class="fa fa-check-square-o checked" aria-hidden="true"></i>
          <% end %>
        </div>
        <div>
            Retailer: <%= national.retailer.label %>
        </div>
      </div>
      <ul class="list-inline product-controls hidden-sm hidden-xs">
        <li>
          <%= link_to edit_national_path(national) do %>
            <i class="fa fa-pencil"> </i>
          <% end %>
        </li>
        <li>
          <%= link_to category_path(category), method: :delete do %>
            <i class="fa fa-trash"> </i>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
<% else %>
  <!--Message is displayed if the list is empty -->
  <%= render "components/no-result-found" %>
<% end %>

app/views/nationals/_nationals-search.html.erb
<div class="search-width">
  <%= form_tag nationals_path, class: "form-inline" , method: "get" do %>
    <%= render "components/search-bar-2" %>
    <%= link_to new_national_path do %>
      <button type="button" name="New" class="btn action spacing-search">New</button>
    <% end %>
  <% end %>
</div>

app/views/nationals/index.html.erb
<div class="work-area">
  <h2>National centrals</h2>
  <!--Search area -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <%= render "nationals-search" %>
      </div>
    </div>
  </div>
  <!-- results list -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <%= render "nationals-list" %>
    </div>
  </div>
</div>

app/views/nationals/new.html.erb
<div class="work-area">
  <h2>New national </h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render "national_form" %>
      </div>
    </div>
  </div>
</div>

app/views/nationals/update.html.erb
<div class="work-area">
  <h2>Edit national </h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render "national_form" %>
      </div>
    </div>
  </div>
</div>