config/routes.rb
Rails.application.routes.draw do


  # Route to manage Attachinary
  mount Attachinary::Engine => "/attachinary"

  # Routes related to the users
  devise_for :users
  resources :users, only: [:index]

  root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  # Routes related to products
  get "products" => "products#index"
  get "products/:id" => "products#show"


  # Routes related to users management
  resources :categories

  # Routes related to the countries mangement
  resources :countries

  # Routes related to the groups mangement
  resources :groups

  # Routes related to the markets mangement
  resources :markets

  # Routes related to the nationals mangement
  resources :nationals

  # Routes related to the profils mangement
  resources :profils

  # Routes related to the post mangement
  resources :posts

  # Routes related to the regionals mangement
  resources :regionals

  # Routes related to the retailers mangement
  resources :retailers


  namespace :dynamic_select do
    get ':country_id/countries', to: 'categories#index', as: 'countries'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/shared/_flashes.html.erb
<!-- De activate for improving user experience
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
-->

<!-- Alert Log or Pwd are invalid when user try to log in -->
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag src="logo.png" %>
  </a>


    <!-- Verify first if the user is looged to access to the menu -->
    <!-- Right Navigation -->

      <% if user_signed_in? %>
        <div class="navbar-wagon-right hidden-xs hidden-sm">

          <!-- Technical screens links -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-technical" data-toggle="dropdown">Technical data</span>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to "Countries", countries_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Categories", categories_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Markets", markets_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
              </ul>
            </div>
          </div>

          <!-- Users screens links -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-users" data-toggle="dropdown">Users</span>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to "Users",users_path,class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Profils", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Groups", class: "navbar-wagon-item navbar-wagon-link" %></li>
              </ul>
            </div>
          </div>

          <!-- Clients screens links -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-clients" data-toggle="dropdown">Clients</span>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to "Retailer",retailers_path ,class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "National central",nationals_path ,class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Local central",regionals_path,class: "navbar-wagon-item navbar-wagon-link" %></li>
              </ul>
            </div>
          </div>

          <!-- Products screens links -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-products" data-toggle="dropdown">Products</span>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to "Innovations", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Etudes", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Gencode management", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "Catalogs", class: "navbar-wagon-item navbar-wagon-link" %></li>
              </ul>
            </div>
          </div>

          <!-- Referencers screens links -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-referencers" data-toggle="dropdown">Referencers</span>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to "My referencers", class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to "All refrencers", class: "navbar-wagon-item navbar-wagon-link" %></li>
              </ul>
            </div>
          </div>

          <!-- Profile picture and dropdown -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <% if current_user.avatar? %>
                <%= cl_image_tag current.user.path, height:60 , width:60, crop: :fill,
                class: "avatar dropdown-toggle", id:"navbar-wagon-menu", :'data-toggle' => 'dropdown' %>
              <% else %>
                <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><a href="#">Profile</a></li>
                <li><a href="#">Dashboard</a></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </div>
          </div>
        </div>
      <% else %>
        <div class="navbar-wagon-item">
          <%= link_to "Connexion", new_user_session_path,class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Inscription", new_user_registration_path,class: "navbar-wagon-item navbar-wagon-link" %>
        </div>
      <% end %>

</div>