config/routes.rb
Rails.application.routes.draw do


  # Route to manage Attachinary
  mount Attachinary::Engine => "/attachinary"

  # Routes related to the users
  devise_for :users
  resources :users, only: [:index]

  root to: 'pages#home'
  get "/team" => "pages#team"
  get "/contact" => "pages#join_us"


  # Routes related to products
  get "products" => "products#index"
  get "products/:id" => "products#show"


  # Routes related to users management
  resources :categories

  # Routes related to the countries mangement
  resources :countries

  # Routes related to the groups mangement
  resources :groups

  # Routes related to the markets mangement
  resources :markets

  # Routes related to the nationals mangement
  resources :nationals

  # Routes related to the profils mangement
  resources :profils

  # Routes related to the post mangement
  resources :posts

  # Routes related to the regionals mangement
  resources :regionals

  # Routes related to the retailers mangement
  resources :retailers


  namespace :dynamic_select do
    get ':country_id/countries', to: 'categories#index', as: 'countries'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  #############################################################################
  # Data  model relationships
  #############################################################################
  has_attachment :photo

  belongs_to :country

  #############################################################################
  # Controls before data records`
  #
  #############################################################################
  validates :code,
            presence: true,
            uniqueness: true,
            length: {maximum: 3}

  validates :label,
            presence: true,
            length: {maximum: 40}


  validates :country_id,
            presence:true

  #############################################################################
  # Scope on set data`
  #############################################################################

  # Scope on the active countries
  scope :active, -> {
    where(:active => true)
  }

  scope :search, -> (query){
    where("code like :query or label like :query", query: "%#{query}%")
  }
 

end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

  before_action :find_retailer, only: [:show,:edit,:update,:destroy]
 
  # Gathering active countries and not master to attach to retailer to create or update
  before_action :find_active_countries_not_master, only: [:new, :edit]

  def index
    @retailers = Retailer.all
    @retailers = @retailers.active if params[:active]
    @retailers = @retailers.search(params[:search]) if params[:search]
  end

  def show
  end

  def new
    @retailer = Retailer.new
  end

  def create
    @retailer = Retailer.new(retailer_params)
    if @retailer.save
      redirect_to retailers_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @retailer.update(retailer_params)
      redirect_to retailers_path
    else
      render :edit
    end
  end

  def destroy
    @retailer.destroy
    redirect_to retailers_path
  end


  private

  # Avoid paramters hacking
  def retailer_params
    params.require(:retailer).permit(:code,:label, :active,:description,:country_id,:photo)
  end

  def find_retailer
    @retailer = Retailer.find(params[:id])
  end

  def find_active_countries_not_master
    @selectable_countries = Country.notMasterAndActive
  end

  
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_retailer-form.html.erb
<%= simple_form_for @retailer do |r| %>
  <%= r.input :code %>
  <%= r.input :label %>
  <%= r.association :country, collection: @selectable_countries.order(:label),:label_method => lambda { |country| "#{country.code} - #{country.label}"},input_html: { class: 'retailer-country-select' } %>
  <%= r.input :active %>
  <%= r.input :description, as: :text %>
  <%= r.input :photo, as: :attachinary %>
  <div class="buttons-down-form">
    <%= r.button :submit, "Validate", class: "btn validate" %> 
    <button class="btn">
      <%= link_to "Back", retailers_path, class: " navbar-wagon-item navbar-wagon-link" %>
    </button>
  </div>
<% end %>

app/views/retailers/_retailers-list.html.erb
<% if @retailers.length != 0 %>
  <% @retailers.each do |retailer|  %>
    <div class="product">
      <% if retailer.photo? %>
        <!-- Decalre the link to retrieve the photo -->
        <%= cl_image_tag(retailer.photo.path, height: 117, width: 175, crop: :fill, class: 'product-image') %>
      <% else %>
        <img src="http://unsplash.it/300/200" alt="substitute" class="product-image hidden-xs" data-toggle="tooltip" data-placement="left" title="country.description">
      <% end %>
      <div class='product-body'>
        <h3> <%= retailer.code %> <%= retailer.label %> </h3>
        <div>Active: 
          <% if retailer.active == true%>
              <i class="fa fa-check-square-o checked" aria-hidden="true"></i>
          <% end %>
        </div>
        <div>
          Country: <%= retailer.country.label%>
        </div>
      </div>
      <ul class="list-inline product-controls hidden-sm hidden-xs">
        <li>
          <%= link_to edit_retailer_path(retailer) do %>
            <i class="fa fa-pencil"> </i>
          <% end %>
        </li>
        <li>
          <%= link_to retailer_path(retailer), method: :delete do %>
            <i class="fa fa-trash"> </i>
           <% end %>
        </li>
      </ul>
    </div>
  <% end %>
<% else %>
  <!--Message is displayed if the list is empty -->
  <%= render "components/no-result-found" %>
<% end %>

app/views/retailers/_retailers-search.html.erb
<div class="search-width">
  <%= form_tag retailers_path, class: "form-inline" do %>
    <div class="form-group" class="spacing-search">
       <%= text_field_tag :search, params[:search] %>
    </div>
    <div class="form-group" class="spacing-search">
      <%= submit_tag "Search", :name => nil, class:"btn spacing-search"  %>
    </div>
    <%= link_to new_retailer_path do %>
      <button type="button" name="New" class="btn action spacing-search">New</button>
    <% end %>
  <% end %>
</div>

app/views/retailers/edit.html.erb
<div class="work-area">
  <h2>Edit retailer </h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render "retailer-form" %>
      </div>
    </div>
  </div>
</div>

app/views/retailers/index.html.erb
<div class="work-area">
  <h2>Retailers</h2>
  <!--Search area -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <%= render "retailers-search" %>
      </div>
    </div>
  </div>
  <!-- results list -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <%= render "retailers-list" %>
    </div>
  </div>
</div>

app/views/retailers/new.html.erb
<div class="work-area">
  <h2>New retailer </h2>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render "retailer-form" %>
      </div>
    </div>
  </div>
</div>